const DEFAULT_COMMITMENT = "confirmed";

const PUMPFUN_PROGRAM_ID = "6EF8rrecthR5Dkzon8Nwu78hRvfCKubJ14M5uBEwF6P";
const RAYDIUM_LAUNCHPAD_PROGRAM_ID = "LanMV9sAd7wArD4vJFi2qDdfnVhFxYSUg6eADduJ3uj";
const PUMPSWAP_AMM_PROGRAM_ID = "pAMMBay6oceH9fJKBRHGP5D4bD4sWpmSwMn52FMfXEA";
const MOONIT_PROGRAM_ID = "MoonCVVNZFSYkqNXP6bxHLPL6QQJiMagDL3qcqUQTrG";
const RAYDIUM_AMM_PROGRAM_ID = "675kPX9MHTjS2zt1qfr1NYHuzeLXfQM9H24wFSUt1Mp8";

export {
  MOONIT_PROGRAM_ID,
  PUMPFUN_PROGRAM_ID,
  PUMPSWAP_AMM_PROGRAM_ID,
  RAYDIUM_LAUNCHPAD_PROGRAM_ID,
  RAYDIUM_AMM_PROGRAM_ID,
  DEFAULT_COMMITMENT
};
